version: '3.8'

services:
  db:
    build: ./db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: "example"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  server:
    build: ./api
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - /app/node_modules
      - ./api:/app
  client:
    build: ./client
    restart: always
    depends_on:
      - server
    ports:
      - "3000:80"
    volumes:
      - /app/node_modules
      - ./client:/app
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data:
    
    