version: '3.8'

services:
  server:
    build: ./api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - /app/node_modules
      - ./api:/app
  client:
    build: ./client
    restart: always
    depends_on:
      - server
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
    
    