version: '3.8'

services:
  db:
    build: ./db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: "example"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
  server:
    build: ./api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - /app/node_modules
      - ./api:/app
  client:
    build: ./client
    restart: always
    depends_on:
      - server
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
    
    